### ISSUE TITLE
LFS pointer validity check: is it necessary anymore?

### ISSUE THREAD

**Issue by mlbright** [Autodesk/watchdog4git#5]
@larsxschneider in GHE 2.15, we have "Pushes will be rejected if a Git LFS object hasn't been uploaded properly"[1]. Is that aspect of the LFS watchdog redundant now?

[1] https://enterprise.github.com/releases/series/2.15

**Comment by larsxschneider** [comment]
Correct, that aspect is redundant. However, AFAIK `watchdog4git` does more: it checks if a file *should* be in LFS.
